<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../UnitTestsTypes.Application/UnitTestsTypes.Application.csproj" />
    <ProjectReference Include="../UnitTestsTypes.Domain/UnitTestsTypes.Domain.csproj" />
    <ProjectReference Include="../UnitTestsTypes.Infrastructure/UnitTestsTypes.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
  </ItemGroup>

</Project>
